### ISSUE TITLE
Off-screen characters being hittable on tag mode

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#216]
https://user-images.githubusercontent.com/77592586/104858489-67b84880-58fe-11eb-8df5-90c277c74b61.mp4

**Comment by Orochikyocr** [comment]
Are you using 0.96.1 and the default tag.zss file?
This was already reported and it was happening because characters wont get out of the stage totally according to the position of the main player at the moment of the switch.
This was fixed on 0.96.1 and the default tag.

I recommend you share your Ikemen Go version when reporting bugs.

**Comment by UrsoManso** [comment]
Yes, 0.96.1. 
But if by default tag you mean the MvCI esque one then no, I'm using the tag_base.zss
I should've indeed mentioned the version but I assumed that the devs only take bug reports from the latest version because otherwise people would report bugs from previous versions that have been fixed already.

**Comment by Orochikyocr** [comment]
Maybe K4thos forgot to add the fix to the TAG base.
They didn't change the LUA file that points out the Ikemen Go version.

This was the part that was causing the bug, Map(_iksys_tagLeavingPosX) was added after 0.95. for bigger zoom or 720 stages I change 160 to a bigger value to solve this bug.

`if BackEdgeDist < -Const240p(160) || FrontEdgeDist < -Const240p(160) || Map(_iksys_tagLeavingPosX) = Pos X {
	ChangeState{value: Const(StateTagWaitingOutside)}
}

MapSet{map: "_iksys_tagLeavingPosX"; value: Pos X} #TODO: won't be needed once this bug is fixed: https://github.com/Windblade-GR01/Ikemen-GO/issues/171
`

**Comment by UrsoManso** [comment]
I tried changing the values to both 200 and then 300 but neither worked. Here's how it looks:

if BackEdgeDist < -Const240p(300) || FrontEdgeDist < -Const240p(300) || Map(_iksys_tagLeavingPosX) = Pos X {
	ChangeState{value: Const(StateTagWaitingOutside)}
}
MapSet{map: "_iksys_tagLeavingPosX"; value: Pos X}

**Comment by K4thos** [comment]
from what I see in the video this has nothing to do with tag zss code - the bug is in-engine. Standby flag doesn't protect tagged out characters from being hit by projectiles: https://discord.com/channels/233345562261323776/282927929548210177/773731392617185311
So if you create giant projectile with hitbox that can reach even outside the screen, the tagged out team will be hit by it. Gacel already mentioned that he has it mostly fixed.

**Comment by Orochikyocr** [comment]
I remember to fix this by adding a nothitby{ } to the state "waitingoutside". Still not a fix because when you call the partner it doesn't come from the corner as it should but from the part of the stage where it is waiting which looks weird.
So this is pretty much related to the stage and the resolution used. I recommend OP to use the tag.zss instead of tag_base.zss to check if it happens with that file.

**Comment by UrsoManso** [comment]
> I recommend OP to use the tag.zss instead of tag_base.zss to check if it happens with that file.

I've done that right away, same results.

**Comment by K4thos** [comment]
fixed
